import {ref} from 'vue';

export const tags = [
  { id: 1, title: "Проблемные", slug: "pr", color: "#E2BD06" },
  { id: 2, title: "Критические", slug: "cr", color: "#E52E2E" },
  { id: 3, title: "Есть замечания", slug: "cm", color: "#00B6ED" },
  { id: 4, title: "Выполнено", slug: "dn", color: "#00AE5B" },
];

export const county = [
  {
    id: 1,
    icon: "/src/assets/images/RU.svg",
    title: "Россия",
    slug: "RU",
  },
  {
    id: 2,
    icon: "/src/assets/images/TJ.png",
    title: "Таджикистан",
    slug: "TJ",
  },
  {
    id: 3,
    icon: "/src/assets/images/UZ.png",
    title: "Узбекистан",
    slug: "UZ",
  },
];

export const position = [
  { id: 1, title: "Пекарь" },
  { id: 2, title: "Промышленный альпинист" },
  { id: 3, title: "Токарь" },
  { id: 4, title: "Прокрастинатор" },
];

export const type_contract = [
  { id: 1, title: "Гражданско-правовой", slug: "ГПХ" },
  { id: 2, title: "Трудовой", slug: "ТД" },
  { id: 3, title: "Самозанятый", slug: "СМЗ" },
  { id: 4, title: "Кандидат", slug: "КНД" },
];

export const gender = [
  { id: 1, title: "Мужской", slug: "М" },
  { id: 2, title: "Женский", slug: "Ж" },
];

export const workers = ref([
  {
    full_name: "Стас Мое Имя",
    inn: "112323456784",
    address: "г. Санкт-Петербург",
    date_birth: "08.12.1997",
    age: "25",
    type_contract: type_contract[3],
    type_contract_id: type_contract[3].id,
    gender: gender[0],
    gender_id: gender[0].id,
    county: county[0],
    county_id: county[0].id,
    position: position[3],
    position_id: position[3].id,
    status: { tag_id: tags[1].id, tag: tags[1], description: "Не судите строго((" },
  },
  {
    full_name: "ААлоав Василиса Лаааввал",
    inn: "124235693853",
    address: "г. Москва",
    date_birth: "13.02.1990",
    age: "33",
    type_contract: type_contract[3],
    type_contract_id: type_contract[3].id,
    gender: gender[1],
    gender_id: gender[1].id,
    county: county[2],
    county_id: county[2].id,
    position: position[0],
    position_id: position[0].id,
    status: { tag_id: tags[0].id, tag: tags[0], description: "Все плохо" },
  },
  {
    full_name: "Ивано Иван Иваныч",
    inn: "349285647345",
    address: "г. Москва",
    date_birth: "13.02.1990",
    age: "33",
    type_contract: type_contract[0],
    type_contract_id: type_contract[0].id,
    gender: gender[0],
    gender_id: gender[0].id,
    county: county[1],
    county_id: county[1].id,
    position: position[2],
    position_id: position[2].id,
    status: { tag_id: tags[2].id, tag: tags[2], description: "Надо подумать" },
  },
  {
    full_name: "Ивано Иван Иваныч",
    inn: "831492247345",
    address: "г. Москва",
    date_birth: "13.02.1990",
    age: "33",
    type_contract: type_contract[0],
    type_contract_id: type_contract[0].id,
    gender: gender[0],
    gender_id: gender[0].id,
    county: county[0],
    county_id: county[0].id,
    position: position[1],
    position_id: position[1].id,
    status: { tag_id: tags[1].id, tag: tags[1], description: "Ужас какой-то" },
  },
  {
    full_name: "Ивано Иван Иваныч",
    inn: "125496048274",
    address: "г. Москва",
    date_birth: "13.02.1990",
    age: "33",
    type_contract: type_contract[1],
    type_contract_id: type_contract[1].id,
    gender: gender[0],
    gender_id: gender[0].id,
    county: county[1],
    county_id: county[1].id,
    position: position[3],
    position_id: position[3].id,
    status: { tag_id: tags[3].id, tag: tags[3], description: "Молодец" },
  },
  {
    full_name: "Ивано Иван Иваныч",
    inn: "448275649385",
    address: "г. Москва",
    date_birth: "13.02.1990",
    age: "33",
    type_contract: type_contract[2],
    type_contract_id: type_contract[2].id,
    gender: gender[0],
    gender_id: gender[0].id,
    county: county[0],
    county_id: county[0].id,
    position: position[3],
    position_id: position[3].id,
    status: { tag_id: tags[3].id, tag: tags[3], description: "Молодец" },
  },
  {
    full_name: "Ивано Иван Иваныч",
    inn: "194857452856",
    address: "г. Москва",
    date_birth: "13.02.1990",
    age: "33",
    type_contract: type_contract[1],
    type_contract_id: type_contract[1].id,
    gender: gender[0],
    gender_id: gender[0].id,
    county: county[2],
    county_id: county[2].id,
    position: position[0],
    position_id: position[0].id,
    status: { tag_id: tags[1].id, tag: tags[1], description: "Ужас какой-то" },
  },
  {
    full_name: "Ивано Иван Иваныч",
    inn: "111111111111",
    address: "г. Москва",
    date_birth: "13.02.1990",
    age: "33",
    type_contract: type_contract[3],
    type_contract_id: type_contract[3].id,
    gender: gender[0],
    gender_id: gender[0].id,
    county: county[2],
    county_id: county[2].id,
    position: position[1],
    position_id: position[1].id,
    status: { tag_id: 0, tag: tags[0], description: "Все плохо" },
  },
]);
